# Generated by Django 3.0 on 2020-09-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='es_duenio',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
