# Generated by Django 3.0 on 2020-09-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('id_local', models.PositiveIntegerField()),
                ('dia', models.DateField()),
            ],
        ),
    ]
