# Generated by Django 3.0 on 2020-09-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.PositiveIntegerField()),
                ('id_local', models.PositiveIntegerField()),
                ('dia', models.DateField()),
                ('invitado1', models.PositiveIntegerField()),
                ('invitado2', models.PositiveIntegerField()),
                ('invitado3', models.PositiveIntegerField()),
            ],
        ),
    ]
