# Generated by Django 3.0 on 2020-09-28 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0008_auto_20200923_2106'),
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='id_local',
        ),
        migrations.AddField(
            model_name='turnos',
            name='id_local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno_idLocal', to='empresa.Empresa'),
        ),
    ]
