# Generated by Django 3.0 on 2020-09-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='invitado1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='invitado2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='turnos',
            name='invitado3',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
