# Generated by Django 3.0 on 2020-09-24 21:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turnos', '0003_auto_20200924_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turnos',
            name='invitado1',
        ),
        migrations.AddField(
            model_name='turnos',
            name='invitado1',
            field=models.ManyToManyField(blank=True, null=True, related_name='turno_invitado1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='invitado2',
        ),
        migrations.AddField(
            model_name='turnos',
            name='invitado2',
            field=models.ManyToManyField(blank=True, null=True, related_name='turno_invitado2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='turnos',
            name='invitado3',
        ),
        migrations.AddField(
            model_name='turnos',
            name='invitado3',
            field=models.ManyToManyField(blank=True, null=True, related_name='turno_invitado3', to=settings.AUTH_USER_MODEL),
        ),
    ]
