# Generated by Django 3.0 on 2020-09-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('CUIT', models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='CUIT')),
                ('Nombre', models.CharField(max_length=50)),
                ('Superficie', models.PositiveIntegerField()),
                ('Cant_empleados', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Razon_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
