# Generated by Django 3.0 on 2020-09-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('CUIT', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CUIT')),
                ('Nombre', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=80)),
                ('Telefono', models.BigIntegerField(blank=True, null=True)),
                ('PaginaWeb', models.CharField(blank=True, max_length=150, null=True)),
                ('Email', models.CharField(blank=True, max_length=50, null=True)),
                ('HorarioPrimeroAbre', models.CharField(blank=True, max_length=50, null=True)),
                ('HorarioPrimeroCierra', models.CharField(blank=True, max_length=50, null=True)),
                ('HorarioSegundoAbre', models.CharField(blank=True, max_length=50, null=True)),
                ('HorarioSegundoCierra', models.CharField(blank=True, max_length=50, null=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='empresa')),
                ('Superficie', models.BigIntegerField()),
                ('Cant_empleados', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Razon_Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
    ]
