# Generated by Django 3.0 on 2020-09-29 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='DNI',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Razon_Social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='razon_social', to='empresa.Razon_Social'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='Rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubro_empresa', to='empresa.Rubro'),
        ),
    ]
