# Generated by Django 3.0 on 2020-09-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20200923_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Direccion',
            field=models.CharField(default='EnBlanco', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='Telefono',
            field=models.PositiveIntegerField(default=12345678),
            preserve_default=False,
        ),
    ]
