# Generated by Django 3.0 on 2020-09-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20200923_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='CUIT',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='CUIT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Cant_empleados',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Superficie',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
