# Generated by Django 3.0 on 2020-09-29 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoevaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluaciones',
            name='usuario_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_test', to=settings.AUTH_USER_MODEL),
        ),
    ]
