# Generated by Django 3.0 on 2020-09-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoevaluacion', '0002_autoevaluaciones_usuario_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluaciones',
            name='fecha_testPositivo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
