# Generated by Django 3.0 on 2020-09-16 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoevaluacion', '0002_autoevaluaciones_relacion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autoevaluaciones',
            name='relacion_usuario',
        ),
    ]
