# Generated by Django 3.0 on 2020-09-16 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('autoevaluacion', '0003_remove_autoevaluaciones_relacion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluaciones',
            name='usuario_test',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_test', to=settings.AUTH_USER_MODEL),
        ),
    ]
