# Generated by Django 3.0 on 2020-09-16 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoevaluacion', '0004_autoevaluaciones_usuario_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoevaluaciones',
            name='resultado',
            field=models.CharField(default=False, max_length=10),
            preserve_default=False,
        ),
    ]
