# Generated by Django 3.0 on 2020-09-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoevaluacion', '0005_autoevaluaciones_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluaciones',
            name='fiebre',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='autoevaluaciones',
            name='tos',
            field=models.BooleanField(),
        ),
    ]
