# Generated by Django 3.0 on 2020-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoevaluacion', '0006_auto_20200919_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevaluaciones',
            name='fiebre',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')]),
        ),
        migrations.AlterField(
            model_name='autoevaluaciones',
            name='tos',
            field=models.BooleanField(choices=[(True, 'Sí'), (False, 'No')]),
        ),
    ]
