# Generated by Django 3.0 on 2020-09-23 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('duenio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='duenio',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_duenio', to=settings.AUTH_USER_MODEL),
        ),
    ]
