# Generated by Django 3.0 on 2020-09-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_duenio',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
