# Generated by Django 3.0 on 2020-09-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20200913_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento(DD/MM/AAAA)'),
        ),
    ]
