# Generated by Django 3.0 on 2020-09-16 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_autoevaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='autoevaluacion',
        ),
    ]
