# Generated by Django 3.0 on 2020-09-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20200913_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AddField(
            model_name='usuario',
            name='cumpleanio',
            field=models.DateField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(default=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
